name: Compile Tasmota
on:
  workflow_dispatch:
jobs:
  build-vindriktning:
    runs-on: ubuntu-latest
    container:
      image: blakadder/docker-tasmota
    steps:
      - name: Clone and build tasmota
        run: |
          git clone -b master https://github.com/arendst/Tasmota.git /tasmota
          git clone https://github.com/joBr99/tasmo-compile.git /input
          cp /input/vindriktning/platformio_override.ini /tasmota/tasmota/platformio_override.ini
          cp /input/vindriktning/user_config_override.h /tasmota/tasmota/user_config_override.h
          bash /entrypoint.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tasmota-artifacts
          path: |
            /tasmota/build_output/firmware
