name: Compile Tasmota
on:
  workflow_dispatch:
jobs:
  build-vindriktning:
    runs-on: ubuntu-latest
    container:
      image: blakadder/docker-tasmota
    steps:
      - name: test
        run: |
          git clone -b master https://github.com/arendst/Tasmota.git /tasmota
          git clone https://github.com/joBr99/tasmo-compile.git /input
          cp /input/vindriktning/* /tasmota/tasmota/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tasmota-artifacts
          path: |
            /tasmota/build_output/firmware
